### ISSUE TITLE
Expose the selector

### ISSUE THREAD

**Issue by poundbang** [kigawas/web3-input-decoder#113]
Hello,

Nice project. Could you please expose the selector as well from  https://github.com/kigawas/web3-input-decoder/blob/a79b5eff71d61a548e16411c3e87f7fda4e4e327/web3_input_decoder/decoder.py#L41

It will help not to go through figuring out the 4byte to method name separately. Perhaps, via a tuple? 

Thanks.

**Comment by kigawas** [comment]
You can use this function

https://github.com/kigawas/web3-input-decoder/blob/master/web3_input_decoder/utils.py#L25

**Comment by xinxianren** [comment]
I can't decode input data,  result below:

(True, 'exactInput', [('(bytes,address,uint256,uint256,uint256)', 'params', (b"2\xf0D\xda%!\x85\x98\xd4#\x8aO\xc6\x82j\xc4\xeb\xb9~\x9e\x00'\x10\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2\x00\x01\xf4\xda\xc1\x7f\x95\x8d.\xe5#\xa2 b\x06\x99E\x97\xc1=\x83\x1e\xc7", '0xba9779cd74a9f2cef2dac1e3ad7521f0617f18c0', 1685708519, 2815368142784924009454894975, 8756054851))])

how to decode:
b"2\xf0D\xda%!\x85\x98\xd4#\x8aO\xc6\x82j\xc4\xeb\xb9~\x9e\x00'\x10\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2\x00\x01\xf4\xda\xc1\x7f\x95\x8d.\xe5#\xa2 b\x06\x99E\x97\xc1=\x83\x1e\xc7"


router:  uniswap v3 swaprouter 
swaprouter CA: 0xe592427a0aece92de3edee1f18e0157c05861564
and eg. tx :https://etherscan.io/tx/0x6d224bf2ba8718f166ee38f8b8f5b860cc40d88fecd15223b0c5bd1372da00e0

TThanks for you help!

**Comment by xinxianren** [comment]
from web3_input_decoder import decode_constructor, decode_function
from web3_input_decoder.utils import get_constructor_type
addr = "0xe592427a0aece92de3edee1f18e0157c05861564"
from eth_abi import decode

class DecodeUniswapV3RouterInputData():
    def __init__(self):
        self.abi= " router ABI ............"

    def decode_swap_v3_router_function(self, input_data):
        de_fun_result = decode_function(self.abi, input_data)
        return de_fun_result.name, de_fun_result.arguments

    def handle_decoded_input_data(self, de_fun_name,args):
        if de_fun_name == "exactInputSingle":
            return True, de_fun_name, args

        if de_fun_name == "exactOutputSingle":
            return True, de_fun_name, args

        elif de_fun_name == "multicall":
            return True, de_fun_name, decode_function(self.abi, args[0][2][0]).arguments

        else:
            print(f" === other function {de_fun_name} ===> {args}")
            return True,de_fun_name,args


d =DecodeUniswapV3RouterInputData()
input_data="0xc04b8d59000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000ba9779cd74a9f2cef2dac1e3ad7521f0617f18c0000000000000000000000000000000000000000000000000000000006479dee700000000000000000000000000000000000000000918d164d673294e95b3ff7f0000000000000000000000000000000000000000000000000000000209e6cb43" \
           "0000000000000000000000000000000000000000000000000000000000000042" \
           "32f044da25218598d4238a4fc6826ac4ebb97e9e" \
           "002710c" \
           "02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" \
           "0001f4" \
           "dac17f958d2ee523a2206206994597c13d831ec7" \
           "000000000000000000000000000000000000000000000000000000000000"
de_fun_name,args = d.decode_swap_v3_router_function(input_data)
print(d.handle_decoded_input_data(de_fun_name, args))`
