### ISSUE TITLE
How to decode the UniswapV3 multicall function?

### ISSUE THREAD

**Issue by Jonkrua** [kigawas/web3-input-decoder#123]
It seems failed to decode UniswapV3 multicall function ?? I want to decode the  specific function from the tx input data.
<img width="1288" alt="image" src="https://github.com/kigawas/web3-input-decoder/assets/90612055/12154027-66a3-44be-a22b-8783a50f8083">

**Comment by kigawas** [comment]
It's already decoded. You have a "deadline" and a "data"

**Comment by kigawas** [comment]
We don't recursively decode it. You can use the bytes as a new input to decode
