### ISSUE TITLE
Fallback function

### ISSUE THREAD

**Issue by KennBro** [kigawas/web3-input-decoder#132]
Whenever a contract receives Ether with an empty input or cannot match a pre-defined function, its fallback function will be automatically executed.
Have you contemplated that case?
I know that the name of the repo is web3-input-decoder and you must include another elements to add the functionality of detect fallback function, but, again...
Have you contemplated that case to develop any solution?

Thanks a lot for your work

**Comment by kigawas** [comment]
There is generally no input (or bytes input) of a fallback function call, I don't see much necessity.
Let's take an [example](https://solidity-by-example.org/fallback/), as you can see there is no "inputs" field of a fallback function in the ABI.

```solidity
contract FallbackInputOutput {
    address immutable target;

    constructor(address _target) {
        target = _target;
    }

    fallback(bytes calldata data) external payable returns (bytes memory) {
        (bool ok, bytes memory res) = target.call{value: msg.value}(data);
        require(ok, "call failed");
        return res;
    }
}
```

```json
[
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_target",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"stateMutability": "payable",
		"type": "fallback"
	}
]
```

**Comment by KennBro** [comment]
Yes, I know, I'm trying to determine which function is executing a transaction and looking for that function in the source to display it.
Your library has helped me a lot, thank you.
I'm currently handling the exception when the input is empty or has a function that doesn't exist in the contract and I'm trying to determine the fallback function.
Again THANK YOU.
