### ISSUE TITLE
pysha3 fails to install

### ISSUE THREAD

**Issue by Malogna** [kigawas/web3-input-decoder#45]
`         Creating library build\temp.win32-3.8\Release\Modules/_sha3\_pysha3.cp38-win_amd64.lib and object build\temp.win32-3.8\Release\Modules/_sha3\_pysha3.cp38-win_amd64.exp
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyExc_BufferError
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyModule_AddIntConstant
      sha3module.obj : error LNK2001: unresolved external symbol __imp___PyErr_BadInternalCall
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyEval_SaveThread
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyExc_RuntimeError
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromLong
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyThread_allocate_lock
      sha3module.obj : error LNK2001: unresolved external symbol __imp___Py_NoneStruct
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyThread_acquire_lock
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyErr_SetString
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyModule_AddStringConstant
      sha3module.obj : error LNK2001: unresolved external symbol __imp___Py_Dealloc
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyObject_Free
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyThread_release_lock
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyModule_AddObject
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetBuffer
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyModule_Create2
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyType_Ready
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyThread_free_lock
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyMem_Free
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyErr_NoMemory
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyBytes_FromStringAndSize
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyArg_ParseTupleAndKeywords
      sha3module.obj : error LNK2001: unresolved external symbol __imp___PyObject_New
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyExc_TypeError
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyMem_Malloc
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromString
      sha3module.obj : error LNK2001: unresolved external symbol __imp___Py_strhex
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyBuffer_Release
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyType_Type
      sha3module.obj : error LNK2001: unresolved external symbol __imp__PyEval_RestoreThread
      build\lib.win32-3.8\_pysha3.cp38-win_amd64.pyd : fatal error LNK1120: 31 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysha3`

pysha3 is not supported past python 3.5 and upon web3-input-decoder's installation on python 3.8.10, it makes it impossible to install.

**Comment by kigawas** [comment]
What package manager are you using? `pip install` should work

**Comment by Malogna** [comment]
> What package manager are you using? `pip install` should work

i am using `pip install`

**Comment by kigawas** [comment]
Planning switch from pysha3 to pycryptodome

**Comment by kigawas** [comment]
https://github.com/kigawas/web3-input-decoder/runs/6033888667?check_suite_focus=true

It didn't get reproduced in CI. Probably a library configuration issue
