### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by merganon** [kigawas/web3-input-decoder#5]
Hey there, thank you for your work.

```
import json
import urllib.request
from web3_input_decoder import decode_constructor, decode_function

tokenAddress = "0x7D9c8D888d03df89461C645bd1108AE138b63a2A"
input = "0xe8078d94"

f = urllib.request.urlopen("https://api.etherscan.io/api?module=contract&action=getabi&address=" + tokenAddress)
TOKEN_ABI = json.loads(json.load(f)["result"])
decoded = decode_function(TOKEN_ABI, input)
print(decoded)
```

This simple code above is throwing me this error:
```
__init__.py", line 80, in decode_function
type_def = selector_to_type_def[selector]["inputs"]
KeyError: b'\xe8\x07\x8d\x94'
```

Do you by any chance know what causes the issue?

**Comment by kigawas** [comment]
Your input is too short, which could only be a function without arguments.
Can you post the transaction hash?

**Comment by merganon** [comment]
Just solved the issue, I was requesting the wrong contract.
Transaction: https://etherscan.io/tx/0xb9e9197842ab467e29b98cc5db7e2f7a54c90ce9860ba11c6b2bf4e6d776c096

I was trying to fetch `0x7D9c8D888d03df89461C645bd1108AE138b63a2A` (Uniswap liquidity pair) instead of 0x72913FE0Ae6Ca7d85670C3598AdF446eCC3636B3 (their presale contract)

**Comment by kigawas** [comment]
Glad you solved it :)
